### ISSUE TITLE
[Bug] Restarting or Updating Container results in a rescan being necessary [unRAID]

### ISSUE THREAD

**Issue by joshmans** [zurdi15/romm#563] opened 2024-01-03 01:12 UTC
**RomM version**
2.2.1

**Describe the bug**
Anytime the container is "reset" (stopped/started, or updated), a new full scan is required.

**To Reproduce**
1. Stop Container
2. Update Container (Optional)
3. Start Container
4. No content is present, requiring a full rescan of files

**Expected behavior**
The [sqllite] database should holdover and not need to be recreated every time.

**Comment by nodiaque** [comment] 2024-01-03 01:55
pretty sure the problem is your didn't map the database to a persistent storage in unraid template.

- "/path/to/database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set

**Comment by bfenty** [comment] 2024-01-03 16:25
> pretty sure the problem is you didn't map the database to a persistent storage in unraid template.
> 
>     * "/path/to/database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
> 
> 
> Problem you list is not an unraid bug or even docker, you just have to map the sqlite path to a persistent storage.

This is very likely your issue.

**Comment by mattyams** [comment] 2024-01-06 14:04
> pretty sure the problem is you didn't map the database to a persistent storage in unraid template.
> 
>     * "/path/to/database:/romm/database" # [Optional] Only needed if ROMM_DB_DRIVER=sqlite or not set
> 
> 
> Problem you list is not an unraid bug or even docker, you just have to map the sqlite path to a persistent storage.

I was having the exact same problem and this is what fixed it for me.

**Comment by gantoine** [comment] 2024-01-06 14:36
Close this as resolved, I've added an entry to the wiki for it https://github.com/zurdi15/romm/wiki/Troubleshooting

**Closed by gantoine** 2024-01-06 14:36 UTC
Labels: bug
