### ISSUE TITLE
[Bug] Case-sensitivity issue where SNES/ROMS fails but SNES/roms works.

### ISSUE THREAD

**Issue by thestraycat** [zurdi15/romm#356] opened 2023-08-31 02:11 UTC
**RomM version**
Latest (v1.10)

**Describe the bug**
Romm seems to fail on case-sensitivty of the 'roms folder. It seems to fail on '/SNES/ROMS' but will process 'SNES/roms'

**To Reproduce**
Simply rename the roms folder from a platform to ROMS

**Expected behavior**
That romm can process folders regardless of case sensitivity (either roms or ROMS)

**Comment by GAntoine** [comment] 2023-08-31 03:23
Can you post the output of docker logs when the error appears? And what exactly is the behaviour you're seeing?

I'm trying this on macos and it seems to work fine, but FWIW macos doesn't respect case sensitivity for folder names.

**Comment by thestraycat** [comment] 2023-09-01 03:54
Sure.

INFO:     [RomM][2023-09-01 04:52:15] · AAE
WARNING:  [RomM][2023-09-01 04:52:16]   AAE not found in IGDB
Task exception was never retrieved
future: <Task finished name='Task-280' coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py:522> exception=Roms not found for platform AAE. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure>
Traceback (most recent call last):
  File "/back/utils/fs.py", line 226, in get_roms
    fs_single_roms: list[str] = list(os.walk(roms_file_path))[0][2]
IndexError: list index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py", line 524, in _handle_event_internal
    r = await server._trigger_event(data[0], namespace, sid, *data[1:])
  File "/usr/local/lib/python3.10/dist-packages/socketio/asyncio_server.py", line 558, in _trigger_event
    ret = await handler(*args)
  File "/back/endpoints/scan.py", line 88, in scan_handler
    await scan_platforms(platforms, complete_rescan)
  File "/back/endpoints/scan.py", line 48, in scan_platforms
    fs_roms = fs.get_roms(scanned_platform.fs_slug)
  File "/back/utils/fs.py", line 228, in get_roms
    raise RomsNotFoundException(p_slug) from exc
utils.exceptions.RomsNotFoundException: Roms not found for platform AAE. Check RomM folder structure here: https://github.com/zurdi15/romm#-folder-structure

**Comment by GAntoine** [comment] 2023-09-01 13:59
Ok yeah this is definitely a linux vs macos thing, which is why I can't reproduce it. The code expects the library structure to be `/roms/<platform>` or /<platform>/roms`, so `ROMS` is not supported. You'll have to change the name of the folder to `roms` in lowercase.

**Comment by thestraycat** [comment] 2023-09-02 13:37
would it not be better to change the code to be case-insensitive? As lots of people will run this on linux... whats really weird is that the 'platform' was fine in capitals For example this works:

AAE/roms 

Based on the fact that AAE is in capitals and roms has to be lower case surely this needs to be added to the code base???

**Comment by GAntoine** [comment] 2023-09-02 15:08
It's because the platform could be any slug (any string really), and we store it as-is when building the path to each ROM file. The `roms` folder however is hardcoded, and supporting both adds [code complexity](https://superuser.com/a/431346) for something that's trivial to change in the filesystem.

@zurdi15 might have different thoughts on this

**Comment by zurdi15** [comment] 2023-09-03 18:27
Yeah I am with @GAntoine . This could cause a lot of potential problems with how directories are managed in linux because you can have both `roms` and `ROMS` folders in the same node, so it can be problematic when detecting the RomM folder structre. I will test it anyway to see how it behaves but for now I suggest just to rename to `roms`

**Comment by thestraycat** [comment] 2023-09-04 00:58
I hear you, but by renaming the folder from ROMS to roms could potentially break everybodies emulator setups when running on linux, in all due respect, i dont think anyone will want to jeorpardize their rocket-launcher roms paths (which connects the roms to the emulators and manages the link paths) to be compliant with a ROM manager, so you could be excluding a large group of people who would have otherwised used this. is there a reason that ROMM canot use a variable for the roms library rather than a hardcoded link? I mean it would be multiples more flexible if it could... It's hard to bend your potential users to a rigid and strict path format for the sake of using a tool surely?

**Comment by GAntoine** [comment] 2023-09-04 02:03
I can appreciate your reason for wanting to specify the roms folder name.

@zurdi15 Is this the extent of changes that need to happen to support this? I can't test it cause I'm on macos lol https://github.com/zurdi15/romm/tree/roms-folder-name-env

**Comment by zurdi15** [comment] 2023-09-04 13:58
@thestraycat I understand, make sense tho. I need to think about how should be the best UX for this in terms of not overload the docker-compose with small configurations, but the approach @GAntoine made should work good enough. 

I'll test it and let you know.

**Comment by GAntoine** [comment] 2023-09-18 16:20
Hey @thestraycat just wanted to let you know this is now available in `dev-2.0.0-rc.5`, and will be in the upcoming 2.0.0 release.

**Closed** 2023-09-18 16:20 UTC
Labels: bug

**Comment by thestraycat** [comment] 2023-10-24 23:28
@GAntoine - Thanks i'll keep an eye out for it!
